language: node_js
node_js:
  - 10

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then travis_retry scripts/prepare-linux.sh;  fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ];    then travis_retry scripts/prepare-osx.sh;    fi

install: travis_retry npm install

script:
  - echo $TRAVIS_OS_NAME
  - npm version
  - ionic --version
  - cordova --version
  - ng --version
  - npm test

after_success:
  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then echo 'TODO update coverage'; fi

stages:
  - test
  - pack
  - name: deploy
    if: (type = push) AND branch =~ ^(master|v\d+\.\d+)$

jobs:
  include:

    - stage: pack
      script:
        - npm run test:pack && echo 'Npm pack testing is passed'

    - stage: deploy
      script:
        - echo "Building Web Pages ..."
        - npm run build:browser:prod
        - echo 'app.chatie.io' | tee www/CNAME
        - cp resources/icon.png www/assets/imgs/logo.png
        - echo "Deploying to Surge.sh ..."

      deploy:
        provider: surge
        project: www/
        domain: app.chatie.io
        skip_cleanup: true
        on:
          all_branches: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    on_success: change
    on_failure: change
