language: node_js
node_js:
  - "9"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - jq
      - shellcheck
      - moreutils

cache:
  directories:
    - node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then travis_retry scripts/prepare-linux.sh;  fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ];    then travis_retry scripts/prepare-osx.sh;    fi

stages:
  - test
  - pack
  - name: deploy
    if: branch =~ ^(master|v\d+\.\d+)
        AND (type NOT IN (cron, pull_request))

install: travis_retry npm install

jobs:
  include:
    - stage: test
      script:
        - echo $TRAVIS_OS_NAME
        - npm version
        - ionic --version
        - cordova --version
        - ng --version
        - npm test

      after_success:
        - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then echo 'TODO update coverage'; fi

    - stage: pack
      script:
        - npm run test:pack && echo 'Npm pack testing is passed'

    - stage: deploy
      script:
        - echo "Building Web Pages ..."
        - npm run build:browser:prod
        - echo 'app.chatie.io' | tee www/CNAME
        - cp resources/icon.png www/assets/imgs/logo.png
        - echo "Deploying to Surge.sh ..."

      deploy:
        provider: surge
        project: www/
        domain: app.chatie.io
        skip_cleanup: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    on_success: change
    on_failure: change
